apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: configmap-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: configmap
  displayName: configmap
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - k8s
  - operator
  - configmap
  links:
  - name: Configmap Operator
    url: https://configmap-operator.domain
  maintainers:
  - email: amitvashist7@outlook.com
    name: amit
  maturity: alpha
  provider:
    name: amit
  version: 0.0.0
