apiVersion: webapp.example.com/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp-sample
    app.kubernetes.io/part-of: 03-web-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: 03-web-operator
  name: webapp-sample
spec:
  # TODO(user): Add fields here
